name: Git History

on: pull_request

permissions:
  contents: read

jobs:
  clean:
    name: Clean
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/developerc286/clean_git_history:1.2.1@sha256:406f703c47b5f5c7785ad631d2fa774da5b761bc9e5c42a361f020a4d49d4075
    steps:
      - name: Checkout code.
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Check clean Git history.
        run: clean_git_history "origin/${{ github.base_ref }}"
