FROM alpine:3.23.3@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659
{%- if uses_git %}

RUN apk add --no-cache \
    git=2.52.0-r0 && \
    git config --system --add safe.directory '*'
{%- endif %}

ARG TARGET
COPY ./target/${TARGET}/release/{{ project_name }} /usr/local/bin/

WORKDIR /workspace

ENTRYPOINT ["{{ project_name }}"]
