FROM alpine:3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
{%- if uses_git %}

RUN apk add --no-cache \
    git=2.54.0-r0 && \
    git config --system --add safe.directory '*'
{%- endif %}

ARG TARGET
COPY ./target/${TARGET}/release/{{ project_name }} /usr/local/bin/

WORKDIR /workspace

ENTRYPOINT ["{{ project_name }}"]
